DROP TABLE CLIENTES

DROP TABLE PEDIDOS

DROP TABLE LOG_RODADAS

DROP TABLE TIERS

DROP TABLE INTEGRACAO_ARQUIVOS

DROP FUNCTION dbo.VALIDA_EMAIL

DROP FUNCTION dbo.MES_ANIVERSARIO

DROP FUNCTION dbo.RETORNA_TIER

DROP PROCEDURE GETFILES

DROP PROCEDURE INTEGRACAO_CLIENTES

DROP PROCEDURE INTEGRACAO_PEDIDOS

DROP PROCEDURE INTEGRACAO_PMITG

DROP VIEW CONS_RFV