USE [DB_PMITG_FGOS]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[RETORNA_TIER] (@VALOR NUMERIC(15,2))
RETURNS VARCHAR(200)
AS
BEGIN

	DECLARE @TIER VARCHAR(200)


	SELECT @TIER = FAIXA
	  FROM TIERS
         WHERE @VALOR BETWEEN VALOR_COMPRADO_INICIAL AND VALOR_COMPRADO_FINAL

	RETURN @TIER

END
GO
